version: 2

jobs:
  dummy:
    parallelism: 1
    working_directory: ~/work
    docker:
      - image: ruby:2.6.3
    steps:
      - checkout
  rubycritic:
    environment:
      REPORT_PATH: /report 
      BASE_BRANCH: master
    parallelism: 1
    working_directory: ~/work
    docker:
      - image: ruby:2.6.3
    steps:
      - checkout
      - run:
          name: rubycritic
          command: .circleci/rubycritic.sh
      - store_artifacts:
          path: /report

workflows:
  version: 2
  build:
    jobs:
      - dummy:
          filters:
            branches:
              only: dummy

