version: 2

jobs:
  rubycritic:
    environment:
      REPORT_PATH: /report 
    parallelism: 1
    working_directory: ~/work
    docker:
      - image: ruby:2.6.3
    steps:
      - checkout
      - run:
          command: |
            if [ "$CI_PULL_REQUEST" = "" ]; then
              echo 'skip: PR not create yet'
              exit 0
            fi

            export PR_NUMBER=`echo $CI_PULL_REQUEST | awk -F/ '{print $(NF-0)}'`
            gem install -N rubycritic

            # NOTE: 比較するmasterブランチの最新状態にする
            current_branch=`git symbolic-ref --short HEAD` 
            git fetch origin
            git checkout master
            git reset --hard origin/master
            git checkout $current_branch

            mkdir -p ${REPORT_PATH}
            rubycritic -t 100 --mode-ci master --no-browser -p ${REPORT_PATH} ./app ./lib
            .circleci/pr_comment.sh

      - store_artifacts:
          path: /report

workflows:
  version: 2
  build:
    jobs:
      - rubycritic
