version: 2

jobs:
  dummy:
    parallelism: 1
    working_directory: ~/work
    environment:
      RAILS_ENV: test
    docker:
      - image: ruby:2.6.3
    steps:
      - checkout
  rubycritic:
    environment:
      REPORT_PATH: /report 
      BASE_BRANCH: master
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
    parallelism: 1
    working_directory: ~/work
    docker:
      - image: ruby:2.6.3
    steps:
      - checkout
      - run:
          name: rubycritic
          command: .circleci/rubycritic.sh
      - store_artifacts:
          path: /report
      - restore_cache:
          keys:
            - ptolemy-bundler-v1-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundle install
          command: bundle install
      - save_cache:
          name: Saving Cache - Bundler
          key: ptolemy-bundler-v1-{{ checksum "Gemfile.lock" }}
          paths: vendor/bundle
      - run:
          name: reviewdog
          command: |
            curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s
            export REVIEWDOG_GITHUB_API_TOKEN=$GITHUB_ACCESS_TOKEN
            bundle exec rubocop | ./bin/reviewdog -f=rubocop -reporter=github-pr-review

workflows:
  version: 2
  build:
    jobs:
      - dummy
